Test regular grid
bp/resqpy pull request #405
Opened 2022-01-28 16:17 UTC by maxm17

Could add more tests for half_cell_transmissibility.

2022-02-01 17:37 UTC, andy-beer commented on tests/unit_tests/grid/test_regular_grid.py
> +def test_volume_faulted_grid(faulted_grid):
The faulted_grid is not a RegularGrid, so this test, along with test_thickness_faulted_grid() should probably be relocated to a different test module.

2022-02-01 17:38 UTC, andy-beer commented on tests/unit_tests/grid/test_regular_grid.py
> +def test_thickness_faulted_grid(faulted_grid):
See comment for test_volume_faulted_grid()

2022-02-01 17:40 UTC, andy-beer requested changes
Please move the two faulted_grid test functions into a different test module (the faulted grid is not a regular grid).

2022-02-02 09:29 UTC, maxm17 commented
@andy-beer Apologies, moved now

2022-02-02 14:38 UTC, merged