defensive coding fix for set_face_set_gcs_list_from_dict function
bp/resqpy pull request #408
Opened 2022-01-31 15:15 UTC by andy-beer

resolves issue #401

2022-01-31 16:03 UTC, maxm17 requested changes

2022-01-31 16:03 UTC, maxm17 commented on resqpy/grid/face_functions.py
> +            raise Exception('grid face set dictionary item messed up')
I would change the Exception to a ValueError

2022-01-31 17:07 UTC, andy-beer commented
Thanks for those comments @maxm17 – all 3 changes made as suggested.

2022-01-31 17:09 UTC, andy-beer commented
Max, I couldn't find the unit test that had flagged up this bug.  Maybe I was looking in the wrong branch.  Anyway, could you please track down the test and run it against this branch?  Or if that is not convenient, I think we can safely merge this branch into master.

2022-02-01 10:34 UTC, maxm17 commented
@andy-beer It may be better if you could check that it is working correctly, as I don't know what is expected. The test is in master: unit_tests/grid/test_faults.py::test_find_faults_create_organizing_objects_where_needed_true. You will need to uncomment the act and assertion lines

2022-02-01 16:19 UTC, maxm17 approved these changes

2022-02-01 16:20 UTC, merged